/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrderFreeQuransRouteImport } from './routes/order-free-qurans'
import { Route as DistributeRouteImport } from './routes/distribute'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BackendRouteRouteImport } from './routes/backend/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIndexRouteImport } from './routes/videos/index'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as QuranIndexRouteImport } from './routes/quran/index'
import { Route as DonateIndexRouteImport } from './routes/donate/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as BackendIndexRouteImport } from './routes/backend/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as VideosSlugRouteImport } from './routes/videos/$slug'
import { Route as QuranSlugRouteImport } from './routes/quran/$slug'
import { Route as DonateCheckoutRouteImport } from './routes/donate/checkout'
import { Route as DonateCartRouteImport } from './routes/donate/cart'
import { Route as DonateSlugRouteImport } from './routes/donate/$slug'
import { Route as BooksSlugRouteImport } from './routes/books/$slug'
import { Route as BackendVideosRouteImport } from './routes/backend/videos'
import { Route as BackendVentureRouteImport } from './routes/backend/venture'
import { Route as BackendUsersRouteImport } from './routes/backend/users'
import { Route as BackendTrustContentRouteImport } from './routes/backend/trust-content'
import { Route as BackendStoriesRouteImport } from './routes/backend/stories'
import { Route as BackendSiteRouteImport } from './routes/backend/site'
import { Route as BackendSignupRouteImport } from './routes/backend/signup'
import { Route as BackendResetPasswordRouteImport } from './routes/backend/reset-password'
import { Route as BackendQuranWikiRouteImport } from './routes/backend/quran-wiki'
import { Route as BackendQuranEditionsRouteImport } from './routes/backend/quran-editions'
import { Route as BackendProductsRouteImport } from './routes/backend/products'
import { Route as BackendLoginRouteImport } from './routes/backend/login'
import { Route as BackendHeroRouteImport } from './routes/backend/hero'
import { Route as BackendForgotPasswordRouteImport } from './routes/backend/forgot-password'
import { Route as BackendDonationsRouteImport } from './routes/backend/donations'
import { Route as BackendBooksRouteImport } from './routes/backend/books'
import { Route as BackendArticlesRouteImport } from './routes/backend/articles'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as ApiPaypalWebhookRouteImport } from './routes/api/paypal-webhook'
import { Route as AccountResetPasswordRouteImport } from './routes/account/reset-password'
import { Route as AccountRegisterRouteImport } from './routes/account/register'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as AccountForgotPasswordRouteImport } from './routes/account/forgot-password'
import { Route as BackendSettingsRouteRouteImport } from './routes/backend/settings/route'
import { Route as BackendSubmissionsIndexRouteImport } from './routes/backend/submissions/index'
import { Route as BackendSettingsIndexRouteImport } from './routes/backend/settings/index'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as DonateCheckoutSuccessRouteImport } from './routes/donate/checkout/success'
import { Route as DonateCheckoutPaypalReturnRouteImport } from './routes/donate/checkout/paypal-return'
import { Route as DonateCheckoutCancelRouteImport } from './routes/donate/checkout/cancel'
import { Route as BackendSubmissionsFreeQuranRouteImport } from './routes/backend/submissions/free-quran'
import { Route as BackendSubmissionsDistributorRouteImport } from './routes/backend/submissions/distributor'
import { Route as BackendSubmissionsContactRouteImport } from './routes/backend/submissions/contact'
import { Route as BackendSettingsUsersRouteImport } from './routes/backend/settings/users'
import { Route as BackendSettingsSocialRouteImport } from './routes/backend/settings/social'
import { Route as BackendSettingsPaymentsRouteImport } from './routes/backend/settings/payments'
import { Route as BackendSettingsNavigationRouteImport } from './routes/backend/settings/navigation'
import { Route as BackendSettingsFooterRouteImport } from './routes/backend/settings/footer'
import { Route as BackendSettingsBrandingRouteImport } from './routes/backend/settings/branding'
import { Route as BackendSettingsAppsRouteImport } from './routes/backend/settings/apps'
import { Route as BackendInboxSubmissionsRouteImport } from './routes/backend/inbox/submissions'
import { Route as BackendContentVideosRouteImport } from './routes/backend/content/videos'
import { Route as BackendContentVentureRouteImport } from './routes/backend/content/venture'
import { Route as BackendContentTrustContentRouteImport } from './routes/backend/content/trust-content'
import { Route as BackendContentStoriesRouteImport } from './routes/backend/content/stories'
import { Route as BackendContentQuranWikiRouteImport } from './routes/backend/content/quran-wiki'
import { Route as BackendContentQuranEditionsRouteImport } from './routes/backend/content/quran-editions'
import { Route as BackendContentHeroRouteImport } from './routes/backend/content/hero'
import { Route as BackendContentBooksRouteImport } from './routes/backend/content/books'
import { Route as BackendContentArticlesRouteImport } from './routes/backend/content/articles'
import { Route as BackendCommerceProductsRouteImport } from './routes/backend/commerce/products'
import { Route as BackendCommerceDonationsRouteImport } from './routes/backend/commerce/donations'
import { Route as AccountOrdersReferenceRouteImport } from './routes/account/orders/$reference'

const OrderFreeQuransRoute = OrderFreeQuransRouteImport.update({
  id: '/order-free-qurans',
  path: '/order-free-qurans',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributeRoute = DistributeRouteImport.update({
  id: '/distribute',
  path: '/distribute',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendRouteRoute = BackendRouteRouteImport.update({
  id: '/backend',
  path: '/backend',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranIndexRoute = QuranIndexRouteImport.update({
  id: '/quran/',
  path: '/quran/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateIndexRoute = DonateIndexRouteImport.update({
  id: '/donate/',
  path: '/donate/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendIndexRoute = BackendIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackendRouteRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosSlugRoute = VideosSlugRouteImport.update({
  id: '/videos/$slug',
  path: '/videos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranSlugRoute = QuranSlugRouteImport.update({
  id: '/quran/$slug',
  path: '/quran/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateCheckoutRoute = DonateCheckoutRouteImport.update({
  id: '/donate/checkout',
  path: '/donate/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateCartRoute = DonateCartRouteImport.update({
  id: '/donate/cart',
  path: '/donate/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateSlugRoute = DonateSlugRouteImport.update({
  id: '/donate/$slug',
  path: '/donate/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/books/$slug',
  path: '/books/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendVideosRoute = BackendVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendVentureRoute = BackendVentureRouteImport.update({
  id: '/venture',
  path: '/venture',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendUsersRoute = BackendUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendTrustContentRoute = BackendTrustContentRouteImport.update({
  id: '/trust-content',
  path: '/trust-content',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendStoriesRoute = BackendStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendSiteRoute = BackendSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendSignupRoute = BackendSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendResetPasswordRoute = BackendResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendQuranWikiRoute = BackendQuranWikiRouteImport.update({
  id: '/quran-wiki',
  path: '/quran-wiki',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendQuranEditionsRoute = BackendQuranEditionsRouteImport.update({
  id: '/quran-editions',
  path: '/quran-editions',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendProductsRoute = BackendProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendLoginRoute = BackendLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendHeroRoute = BackendHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendForgotPasswordRoute = BackendForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendDonationsRoute = BackendDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendBooksRoute = BackendBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendArticlesRoute = BackendArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => BackendRouteRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaypalWebhookRoute = ApiPaypalWebhookRouteImport.update({
  id: '/api/paypal-webhook',
  path: '/api/paypal-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/account/reset-password',
  path: '/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/account/register',
  path: '/account/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/account/forgot-password',
  path: '/account/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendSettingsRouteRoute = BackendSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendSubmissionsIndexRoute = BackendSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendSettingsIndexRoute = BackendSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackendSettingsRouteRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/account/orders/',
  path: '/account/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateCheckoutSuccessRoute = DonateCheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => DonateCheckoutRoute,
} as any)
const DonateCheckoutPaypalReturnRoute =
  DonateCheckoutPaypalReturnRouteImport.update({
    id: '/paypal-return',
    path: '/paypal-return',
    getParentRoute: () => DonateCheckoutRoute,
  } as any)
const DonateCheckoutCancelRoute = DonateCheckoutCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => DonateCheckoutRoute,
} as any)
const BackendSubmissionsFreeQuranRoute =
  BackendSubmissionsFreeQuranRouteImport.update({
    id: '/submissions/free-quran',
    path: '/submissions/free-quran',
    getParentRoute: () => BackendRouteRoute,
  } as any)
const BackendSubmissionsDistributorRoute =
  BackendSubmissionsDistributorRouteImport.update({
    id: '/submissions/distributor',
    path: '/submissions/distributor',
    getParentRoute: () => BackendRouteRoute,
  } as any)
const BackendSubmissionsContactRoute =
  BackendSubmissionsContactRouteImport.update({
    id: '/submissions/contact',
    path: '/submissions/contact',
    getParentRoute: () => BackendRouteRoute,
  } as any)
const BackendSettingsUsersRoute = BackendSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => BackendSettingsRouteRoute,
} as any)
const BackendSettingsSocialRoute = BackendSettingsSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => BackendSettingsRouteRoute,
} as any)
const BackendSettingsPaymentsRoute = BackendSettingsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => BackendSettingsRouteRoute,
} as any)
const BackendSettingsNavigationRoute =
  BackendSettingsNavigationRouteImport.update({
    id: '/navigation',
    path: '/navigation',
    getParentRoute: () => BackendSettingsRouteRoute,
  } as any)
const BackendSettingsFooterRoute = BackendSettingsFooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => BackendSettingsRouteRoute,
} as any)
const BackendSettingsBrandingRoute = BackendSettingsBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => BackendSettingsRouteRoute,
} as any)
const BackendSettingsAppsRoute = BackendSettingsAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => BackendSettingsRouteRoute,
} as any)
const BackendInboxSubmissionsRoute = BackendInboxSubmissionsRouteImport.update({
  id: '/inbox/submissions',
  path: '/inbox/submissions',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendContentVideosRoute = BackendContentVideosRouteImport.update({
  id: '/content/videos',
  path: '/content/videos',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendContentVentureRoute = BackendContentVentureRouteImport.update({
  id: '/content/venture',
  path: '/content/venture',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendContentTrustContentRoute =
  BackendContentTrustContentRouteImport.update({
    id: '/content/trust-content',
    path: '/content/trust-content',
    getParentRoute: () => BackendRouteRoute,
  } as any)
const BackendContentStoriesRoute = BackendContentStoriesRouteImport.update({
  id: '/content/stories',
  path: '/content/stories',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendContentQuranWikiRoute = BackendContentQuranWikiRouteImport.update({
  id: '/content/quran-wiki',
  path: '/content/quran-wiki',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendContentQuranEditionsRoute =
  BackendContentQuranEditionsRouteImport.update({
    id: '/content/quran-editions',
    path: '/content/quran-editions',
    getParentRoute: () => BackendRouteRoute,
  } as any)
const BackendContentHeroRoute = BackendContentHeroRouteImport.update({
  id: '/content/hero',
  path: '/content/hero',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendContentBooksRoute = BackendContentBooksRouteImport.update({
  id: '/content/books',
  path: '/content/books',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendContentArticlesRoute = BackendContentArticlesRouteImport.update({
  id: '/content/articles',
  path: '/content/articles',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCommerceProductsRoute = BackendCommerceProductsRouteImport.update({
  id: '/commerce/products',
  path: '/commerce/products',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendCommerceDonationsRoute =
  BackendCommerceDonationsRouteImport.update({
    id: '/commerce/donations',
    path: '/commerce/donations',
    getParentRoute: () => BackendRouteRoute,
  } as any)
const AccountOrdersReferenceRoute = AccountOrdersReferenceRouteImport.update({
  id: '/account/orders/$reference',
  path: '/account/orders/$reference',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backend': typeof BackendRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/distribute': typeof DistributeRoute
  '/order-free-qurans': typeof OrderFreeQuransRoute
  '/backend/settings': typeof BackendSettingsRouteRouteWithChildren
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/api/paypal-webhook': typeof ApiPaypalWebhookRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/backend/articles': typeof BackendArticlesRoute
  '/backend/books': typeof BackendBooksRoute
  '/backend/donations': typeof BackendDonationsRoute
  '/backend/forgot-password': typeof BackendForgotPasswordRoute
  '/backend/hero': typeof BackendHeroRoute
  '/backend/login': typeof BackendLoginRoute
  '/backend/products': typeof BackendProductsRoute
  '/backend/quran-editions': typeof BackendQuranEditionsRoute
  '/backend/quran-wiki': typeof BackendQuranWikiRoute
  '/backend/reset-password': typeof BackendResetPasswordRoute
  '/backend/signup': typeof BackendSignupRoute
  '/backend/site': typeof BackendSiteRoute
  '/backend/stories': typeof BackendStoriesRoute
  '/backend/trust-content': typeof BackendTrustContentRoute
  '/backend/users': typeof BackendUsersRoute
  '/backend/venture': typeof BackendVentureRoute
  '/backend/videos': typeof BackendVideosRoute
  '/books/$slug': typeof BooksSlugRoute
  '/donate/$slug': typeof DonateSlugRoute
  '/donate/cart': typeof DonateCartRoute
  '/donate/checkout': typeof DonateCheckoutRouteWithChildren
  '/quran/$slug': typeof QuranSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/backend/': typeof BackendIndexRoute
  '/books/': typeof BooksIndexRoute
  '/donate/': typeof DonateIndexRoute
  '/quran/': typeof QuranIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/account/orders/$reference': typeof AccountOrdersReferenceRoute
  '/backend/commerce/donations': typeof BackendCommerceDonationsRoute
  '/backend/commerce/products': typeof BackendCommerceProductsRoute
  '/backend/content/articles': typeof BackendContentArticlesRoute
  '/backend/content/books': typeof BackendContentBooksRoute
  '/backend/content/hero': typeof BackendContentHeroRoute
  '/backend/content/quran-editions': typeof BackendContentQuranEditionsRoute
  '/backend/content/quran-wiki': typeof BackendContentQuranWikiRoute
  '/backend/content/stories': typeof BackendContentStoriesRoute
  '/backend/content/trust-content': typeof BackendContentTrustContentRoute
  '/backend/content/venture': typeof BackendContentVentureRoute
  '/backend/content/videos': typeof BackendContentVideosRoute
  '/backend/inbox/submissions': typeof BackendInboxSubmissionsRoute
  '/backend/settings/apps': typeof BackendSettingsAppsRoute
  '/backend/settings/branding': typeof BackendSettingsBrandingRoute
  '/backend/settings/footer': typeof BackendSettingsFooterRoute
  '/backend/settings/navigation': typeof BackendSettingsNavigationRoute
  '/backend/settings/payments': typeof BackendSettingsPaymentsRoute
  '/backend/settings/social': typeof BackendSettingsSocialRoute
  '/backend/settings/users': typeof BackendSettingsUsersRoute
  '/backend/submissions/contact': typeof BackendSubmissionsContactRoute
  '/backend/submissions/distributor': typeof BackendSubmissionsDistributorRoute
  '/backend/submissions/free-quran': typeof BackendSubmissionsFreeQuranRoute
  '/donate/checkout/cancel': typeof DonateCheckoutCancelRoute
  '/donate/checkout/paypal-return': typeof DonateCheckoutPaypalReturnRoute
  '/donate/checkout/success': typeof DonateCheckoutSuccessRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/backend/settings/': typeof BackendSettingsIndexRoute
  '/backend/submissions/': typeof BackendSubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/distribute': typeof DistributeRoute
  '/order-free-qurans': typeof OrderFreeQuransRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/api/paypal-webhook': typeof ApiPaypalWebhookRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/backend/articles': typeof BackendArticlesRoute
  '/backend/books': typeof BackendBooksRoute
  '/backend/donations': typeof BackendDonationsRoute
  '/backend/forgot-password': typeof BackendForgotPasswordRoute
  '/backend/hero': typeof BackendHeroRoute
  '/backend/login': typeof BackendLoginRoute
  '/backend/products': typeof BackendProductsRoute
  '/backend/quran-editions': typeof BackendQuranEditionsRoute
  '/backend/quran-wiki': typeof BackendQuranWikiRoute
  '/backend/reset-password': typeof BackendResetPasswordRoute
  '/backend/signup': typeof BackendSignupRoute
  '/backend/site': typeof BackendSiteRoute
  '/backend/stories': typeof BackendStoriesRoute
  '/backend/trust-content': typeof BackendTrustContentRoute
  '/backend/users': typeof BackendUsersRoute
  '/backend/venture': typeof BackendVentureRoute
  '/backend/videos': typeof BackendVideosRoute
  '/books/$slug': typeof BooksSlugRoute
  '/donate/$slug': typeof DonateSlugRoute
  '/donate/cart': typeof DonateCartRoute
  '/donate/checkout': typeof DonateCheckoutRouteWithChildren
  '/quran/$slug': typeof QuranSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/backend': typeof BackendIndexRoute
  '/books': typeof BooksIndexRoute
  '/donate': typeof DonateIndexRoute
  '/quran': typeof QuranIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/videos': typeof VideosIndexRoute
  '/account/orders/$reference': typeof AccountOrdersReferenceRoute
  '/backend/commerce/donations': typeof BackendCommerceDonationsRoute
  '/backend/commerce/products': typeof BackendCommerceProductsRoute
  '/backend/content/articles': typeof BackendContentArticlesRoute
  '/backend/content/books': typeof BackendContentBooksRoute
  '/backend/content/hero': typeof BackendContentHeroRoute
  '/backend/content/quran-editions': typeof BackendContentQuranEditionsRoute
  '/backend/content/quran-wiki': typeof BackendContentQuranWikiRoute
  '/backend/content/stories': typeof BackendContentStoriesRoute
  '/backend/content/trust-content': typeof BackendContentTrustContentRoute
  '/backend/content/venture': typeof BackendContentVentureRoute
  '/backend/content/videos': typeof BackendContentVideosRoute
  '/backend/inbox/submissions': typeof BackendInboxSubmissionsRoute
  '/backend/settings/apps': typeof BackendSettingsAppsRoute
  '/backend/settings/branding': typeof BackendSettingsBrandingRoute
  '/backend/settings/footer': typeof BackendSettingsFooterRoute
  '/backend/settings/navigation': typeof BackendSettingsNavigationRoute
  '/backend/settings/payments': typeof BackendSettingsPaymentsRoute
  '/backend/settings/social': typeof BackendSettingsSocialRoute
  '/backend/settings/users': typeof BackendSettingsUsersRoute
  '/backend/submissions/contact': typeof BackendSubmissionsContactRoute
  '/backend/submissions/distributor': typeof BackendSubmissionsDistributorRoute
  '/backend/submissions/free-quran': typeof BackendSubmissionsFreeQuranRoute
  '/donate/checkout/cancel': typeof DonateCheckoutCancelRoute
  '/donate/checkout/paypal-return': typeof DonateCheckoutPaypalReturnRoute
  '/donate/checkout/success': typeof DonateCheckoutSuccessRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/backend/settings': typeof BackendSettingsIndexRoute
  '/backend/submissions': typeof BackendSubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backend': typeof BackendRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/distribute': typeof DistributeRoute
  '/order-free-qurans': typeof OrderFreeQuransRoute
  '/backend/settings': typeof BackendSettingsRouteRouteWithChildren
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/api/paypal-webhook': typeof ApiPaypalWebhookRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/backend/articles': typeof BackendArticlesRoute
  '/backend/books': typeof BackendBooksRoute
  '/backend/donations': typeof BackendDonationsRoute
  '/backend/forgot-password': typeof BackendForgotPasswordRoute
  '/backend/hero': typeof BackendHeroRoute
  '/backend/login': typeof BackendLoginRoute
  '/backend/products': typeof BackendProductsRoute
  '/backend/quran-editions': typeof BackendQuranEditionsRoute
  '/backend/quran-wiki': typeof BackendQuranWikiRoute
  '/backend/reset-password': typeof BackendResetPasswordRoute
  '/backend/signup': typeof BackendSignupRoute
  '/backend/site': typeof BackendSiteRoute
  '/backend/stories': typeof BackendStoriesRoute
  '/backend/trust-content': typeof BackendTrustContentRoute
  '/backend/users': typeof BackendUsersRoute
  '/backend/venture': typeof BackendVentureRoute
  '/backend/videos': typeof BackendVideosRoute
  '/books/$slug': typeof BooksSlugRoute
  '/donate/$slug': typeof DonateSlugRoute
  '/donate/cart': typeof DonateCartRoute
  '/donate/checkout': typeof DonateCheckoutRouteWithChildren
  '/quran/$slug': typeof QuranSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/backend/': typeof BackendIndexRoute
  '/books/': typeof BooksIndexRoute
  '/donate/': typeof DonateIndexRoute
  '/quran/': typeof QuranIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/account/orders/$reference': typeof AccountOrdersReferenceRoute
  '/backend/commerce/donations': typeof BackendCommerceDonationsRoute
  '/backend/commerce/products': typeof BackendCommerceProductsRoute
  '/backend/content/articles': typeof BackendContentArticlesRoute
  '/backend/content/books': typeof BackendContentBooksRoute
  '/backend/content/hero': typeof BackendContentHeroRoute
  '/backend/content/quran-editions': typeof BackendContentQuranEditionsRoute
  '/backend/content/quran-wiki': typeof BackendContentQuranWikiRoute
  '/backend/content/stories': typeof BackendContentStoriesRoute
  '/backend/content/trust-content': typeof BackendContentTrustContentRoute
  '/backend/content/venture': typeof BackendContentVentureRoute
  '/backend/content/videos': typeof BackendContentVideosRoute
  '/backend/inbox/submissions': typeof BackendInboxSubmissionsRoute
  '/backend/settings/apps': typeof BackendSettingsAppsRoute
  '/backend/settings/branding': typeof BackendSettingsBrandingRoute
  '/backend/settings/footer': typeof BackendSettingsFooterRoute
  '/backend/settings/navigation': typeof BackendSettingsNavigationRoute
  '/backend/settings/payments': typeof BackendSettingsPaymentsRoute
  '/backend/settings/social': typeof BackendSettingsSocialRoute
  '/backend/settings/users': typeof BackendSettingsUsersRoute
  '/backend/submissions/contact': typeof BackendSubmissionsContactRoute
  '/backend/submissions/distributor': typeof BackendSubmissionsDistributorRoute
  '/backend/submissions/free-quran': typeof BackendSubmissionsFreeQuranRoute
  '/donate/checkout/cancel': typeof DonateCheckoutCancelRoute
  '/donate/checkout/paypal-return': typeof DonateCheckoutPaypalReturnRoute
  '/donate/checkout/success': typeof DonateCheckoutSuccessRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/backend/settings/': typeof BackendSettingsIndexRoute
  '/backend/submissions/': typeof BackendSubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backend'
    | '/$'
    | '/about'
    | '/contact'
    | '/distribute'
    | '/order-free-qurans'
    | '/backend/settings'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/api/paypal-webhook'
    | '/api/stripe-webhook'
    | '/articles/$slug'
    | '/backend/articles'
    | '/backend/books'
    | '/backend/donations'
    | '/backend/forgot-password'
    | '/backend/hero'
    | '/backend/login'
    | '/backend/products'
    | '/backend/quran-editions'
    | '/backend/quran-wiki'
    | '/backend/reset-password'
    | '/backend/signup'
    | '/backend/site'
    | '/backend/stories'
    | '/backend/trust-content'
    | '/backend/users'
    | '/backend/venture'
    | '/backend/videos'
    | '/books/$slug'
    | '/donate/$slug'
    | '/donate/cart'
    | '/donate/checkout'
    | '/quran/$slug'
    | '/videos/$slug'
    | '/articles/'
    | '/backend/'
    | '/books/'
    | '/donate/'
    | '/quran/'
    | '/stories/'
    | '/videos/'
    | '/account/orders/$reference'
    | '/backend/commerce/donations'
    | '/backend/commerce/products'
    | '/backend/content/articles'
    | '/backend/content/books'
    | '/backend/content/hero'
    | '/backend/content/quran-editions'
    | '/backend/content/quran-wiki'
    | '/backend/content/stories'
    | '/backend/content/trust-content'
    | '/backend/content/venture'
    | '/backend/content/videos'
    | '/backend/inbox/submissions'
    | '/backend/settings/apps'
    | '/backend/settings/branding'
    | '/backend/settings/footer'
    | '/backend/settings/navigation'
    | '/backend/settings/payments'
    | '/backend/settings/social'
    | '/backend/settings/users'
    | '/backend/submissions/contact'
    | '/backend/submissions/distributor'
    | '/backend/submissions/free-quran'
    | '/donate/checkout/cancel'
    | '/donate/checkout/paypal-return'
    | '/donate/checkout/success'
    | '/account/orders/'
    | '/backend/settings/'
    | '/backend/submissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/distribute'
    | '/order-free-qurans'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/api/paypal-webhook'
    | '/api/stripe-webhook'
    | '/articles/$slug'
    | '/backend/articles'
    | '/backend/books'
    | '/backend/donations'
    | '/backend/forgot-password'
    | '/backend/hero'
    | '/backend/login'
    | '/backend/products'
    | '/backend/quran-editions'
    | '/backend/quran-wiki'
    | '/backend/reset-password'
    | '/backend/signup'
    | '/backend/site'
    | '/backend/stories'
    | '/backend/trust-content'
    | '/backend/users'
    | '/backend/venture'
    | '/backend/videos'
    | '/books/$slug'
    | '/donate/$slug'
    | '/donate/cart'
    | '/donate/checkout'
    | '/quran/$slug'
    | '/videos/$slug'
    | '/articles'
    | '/backend'
    | '/books'
    | '/donate'
    | '/quran'
    | '/stories'
    | '/videos'
    | '/account/orders/$reference'
    | '/backend/commerce/donations'
    | '/backend/commerce/products'
    | '/backend/content/articles'
    | '/backend/content/books'
    | '/backend/content/hero'
    | '/backend/content/quran-editions'
    | '/backend/content/quran-wiki'
    | '/backend/content/stories'
    | '/backend/content/trust-content'
    | '/backend/content/venture'
    | '/backend/content/videos'
    | '/backend/inbox/submissions'
    | '/backend/settings/apps'
    | '/backend/settings/branding'
    | '/backend/settings/footer'
    | '/backend/settings/navigation'
    | '/backend/settings/payments'
    | '/backend/settings/social'
    | '/backend/settings/users'
    | '/backend/submissions/contact'
    | '/backend/submissions/distributor'
    | '/backend/submissions/free-quran'
    | '/donate/checkout/cancel'
    | '/donate/checkout/paypal-return'
    | '/donate/checkout/success'
    | '/account/orders'
    | '/backend/settings'
    | '/backend/submissions'
  id:
    | '__root__'
    | '/'
    | '/backend'
    | '/$'
    | '/about'
    | '/contact'
    | '/distribute'
    | '/order-free-qurans'
    | '/backend/settings'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/api/paypal-webhook'
    | '/api/stripe-webhook'
    | '/articles/$slug'
    | '/backend/articles'
    | '/backend/books'
    | '/backend/donations'
    | '/backend/forgot-password'
    | '/backend/hero'
    | '/backend/login'
    | '/backend/products'
    | '/backend/quran-editions'
    | '/backend/quran-wiki'
    | '/backend/reset-password'
    | '/backend/signup'
    | '/backend/site'
    | '/backend/stories'
    | '/backend/trust-content'
    | '/backend/users'
    | '/backend/venture'
    | '/backend/videos'
    | '/books/$slug'
    | '/donate/$slug'
    | '/donate/cart'
    | '/donate/checkout'
    | '/quran/$slug'
    | '/videos/$slug'
    | '/articles/'
    | '/backend/'
    | '/books/'
    | '/donate/'
    | '/quran/'
    | '/stories/'
    | '/videos/'
    | '/account/orders/$reference'
    | '/backend/commerce/donations'
    | '/backend/commerce/products'
    | '/backend/content/articles'
    | '/backend/content/books'
    | '/backend/content/hero'
    | '/backend/content/quran-editions'
    | '/backend/content/quran-wiki'
    | '/backend/content/stories'
    | '/backend/content/trust-content'
    | '/backend/content/venture'
    | '/backend/content/videos'
    | '/backend/inbox/submissions'
    | '/backend/settings/apps'
    | '/backend/settings/branding'
    | '/backend/settings/footer'
    | '/backend/settings/navigation'
    | '/backend/settings/payments'
    | '/backend/settings/social'
    | '/backend/settings/users'
    | '/backend/submissions/contact'
    | '/backend/submissions/distributor'
    | '/backend/submissions/free-quran'
    | '/donate/checkout/cancel'
    | '/donate/checkout/paypal-return'
    | '/donate/checkout/success'
    | '/account/orders/'
    | '/backend/settings/'
    | '/backend/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackendRouteRoute: typeof BackendRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DistributeRoute: typeof DistributeRoute
  OrderFreeQuransRoute: typeof OrderFreeQuransRoute
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  ApiPaypalWebhookRoute: typeof ApiPaypalWebhookRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  BooksSlugRoute: typeof BooksSlugRoute
  DonateSlugRoute: typeof DonateSlugRoute
  DonateCartRoute: typeof DonateCartRoute
  DonateCheckoutRoute: typeof DonateCheckoutRouteWithChildren
  QuranSlugRoute: typeof QuranSlugRoute
  VideosSlugRoute: typeof VideosSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  DonateIndexRoute: typeof DonateIndexRoute
  QuranIndexRoute: typeof QuranIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
  VideosIndexRoute: typeof VideosIndexRoute
  AccountOrdersReferenceRoute: typeof AccountOrdersReferenceRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/order-free-qurans': {
      id: '/order-free-qurans'
      path: '/order-free-qurans'
      fullPath: '/order-free-qurans'
      preLoaderRoute: typeof OrderFreeQuransRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribute': {
      id: '/distribute'
      path: '/distribute'
      fullPath: '/distribute'
      preLoaderRoute: typeof DistributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend': {
      id: '/backend'
      path: '/backend'
      fullPath: '/backend'
      preLoaderRoute: typeof BackendRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/': {
      id: '/quran/'
      path: '/quran'
      fullPath: '/quran/'
      preLoaderRoute: typeof QuranIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/': {
      id: '/donate/'
      path: '/donate'
      fullPath: '/donate/'
      preLoaderRoute: typeof DonateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/': {
      id: '/backend/'
      path: '/'
      fullPath: '/backend/'
      preLoaderRoute: typeof BackendIndexRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$slug': {
      id: '/videos/$slug'
      path: '/videos/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof VideosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/$slug': {
      id: '/quran/$slug'
      path: '/quran/$slug'
      fullPath: '/quran/$slug'
      preLoaderRoute: typeof QuranSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/checkout': {
      id: '/donate/checkout'
      path: '/donate/checkout'
      fullPath: '/donate/checkout'
      preLoaderRoute: typeof DonateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/cart': {
      id: '/donate/cart'
      path: '/donate/cart'
      fullPath: '/donate/cart'
      preLoaderRoute: typeof DonateCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/$slug': {
      id: '/donate/$slug'
      path: '/donate/$slug'
      fullPath: '/donate/$slug'
      preLoaderRoute: typeof DonateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/books/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/videos': {
      id: '/backend/videos'
      path: '/videos'
      fullPath: '/backend/videos'
      preLoaderRoute: typeof BackendVideosRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/venture': {
      id: '/backend/venture'
      path: '/venture'
      fullPath: '/backend/venture'
      preLoaderRoute: typeof BackendVentureRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/users': {
      id: '/backend/users'
      path: '/users'
      fullPath: '/backend/users'
      preLoaderRoute: typeof BackendUsersRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/trust-content': {
      id: '/backend/trust-content'
      path: '/trust-content'
      fullPath: '/backend/trust-content'
      preLoaderRoute: typeof BackendTrustContentRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/stories': {
      id: '/backend/stories'
      path: '/stories'
      fullPath: '/backend/stories'
      preLoaderRoute: typeof BackendStoriesRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/site': {
      id: '/backend/site'
      path: '/site'
      fullPath: '/backend/site'
      preLoaderRoute: typeof BackendSiteRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/signup': {
      id: '/backend/signup'
      path: '/signup'
      fullPath: '/backend/signup'
      preLoaderRoute: typeof BackendSignupRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/reset-password': {
      id: '/backend/reset-password'
      path: '/reset-password'
      fullPath: '/backend/reset-password'
      preLoaderRoute: typeof BackendResetPasswordRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/quran-wiki': {
      id: '/backend/quran-wiki'
      path: '/quran-wiki'
      fullPath: '/backend/quran-wiki'
      preLoaderRoute: typeof BackendQuranWikiRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/quran-editions': {
      id: '/backend/quran-editions'
      path: '/quran-editions'
      fullPath: '/backend/quran-editions'
      preLoaderRoute: typeof BackendQuranEditionsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/products': {
      id: '/backend/products'
      path: '/products'
      fullPath: '/backend/products'
      preLoaderRoute: typeof BackendProductsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/login': {
      id: '/backend/login'
      path: '/login'
      fullPath: '/backend/login'
      preLoaderRoute: typeof BackendLoginRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/hero': {
      id: '/backend/hero'
      path: '/hero'
      fullPath: '/backend/hero'
      preLoaderRoute: typeof BackendHeroRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/forgot-password': {
      id: '/backend/forgot-password'
      path: '/forgot-password'
      fullPath: '/backend/forgot-password'
      preLoaderRoute: typeof BackendForgotPasswordRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/donations': {
      id: '/backend/donations'
      path: '/donations'
      fullPath: '/backend/donations'
      preLoaderRoute: typeof BackendDonationsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/books': {
      id: '/backend/books'
      path: '/books'
      fullPath: '/backend/books'
      preLoaderRoute: typeof BackendBooksRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/articles': {
      id: '/backend/articles'
      path: '/articles'
      fullPath: '/backend/articles'
      preLoaderRoute: typeof BackendArticlesRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paypal-webhook': {
      id: '/api/paypal-webhook'
      path: '/api/paypal-webhook'
      fullPath: '/api/paypal-webhook'
      preLoaderRoute: typeof ApiPaypalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register': {
      id: '/account/register'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/account/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/settings': {
      id: '/backend/settings'
      path: '/settings'
      fullPath: '/backend/settings'
      preLoaderRoute: typeof BackendSettingsRouteRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/submissions/': {
      id: '/backend/submissions/'
      path: '/submissions'
      fullPath: '/backend/submissions/'
      preLoaderRoute: typeof BackendSubmissionsIndexRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/settings/': {
      id: '/backend/settings/'
      path: '/'
      fullPath: '/backend/settings/'
      preLoaderRoute: typeof BackendSettingsIndexRouteImport
      parentRoute: typeof BackendSettingsRouteRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/account/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/checkout/success': {
      id: '/donate/checkout/success'
      path: '/success'
      fullPath: '/donate/checkout/success'
      preLoaderRoute: typeof DonateCheckoutSuccessRouteImport
      parentRoute: typeof DonateCheckoutRoute
    }
    '/donate/checkout/paypal-return': {
      id: '/donate/checkout/paypal-return'
      path: '/paypal-return'
      fullPath: '/donate/checkout/paypal-return'
      preLoaderRoute: typeof DonateCheckoutPaypalReturnRouteImport
      parentRoute: typeof DonateCheckoutRoute
    }
    '/donate/checkout/cancel': {
      id: '/donate/checkout/cancel'
      path: '/cancel'
      fullPath: '/donate/checkout/cancel'
      preLoaderRoute: typeof DonateCheckoutCancelRouteImport
      parentRoute: typeof DonateCheckoutRoute
    }
    '/backend/submissions/free-quran': {
      id: '/backend/submissions/free-quran'
      path: '/submissions/free-quran'
      fullPath: '/backend/submissions/free-quran'
      preLoaderRoute: typeof BackendSubmissionsFreeQuranRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/submissions/distributor': {
      id: '/backend/submissions/distributor'
      path: '/submissions/distributor'
      fullPath: '/backend/submissions/distributor'
      preLoaderRoute: typeof BackendSubmissionsDistributorRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/submissions/contact': {
      id: '/backend/submissions/contact'
      path: '/submissions/contact'
      fullPath: '/backend/submissions/contact'
      preLoaderRoute: typeof BackendSubmissionsContactRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/settings/users': {
      id: '/backend/settings/users'
      path: '/users'
      fullPath: '/backend/settings/users'
      preLoaderRoute: typeof BackendSettingsUsersRouteImport
      parentRoute: typeof BackendSettingsRouteRoute
    }
    '/backend/settings/social': {
      id: '/backend/settings/social'
      path: '/social'
      fullPath: '/backend/settings/social'
      preLoaderRoute: typeof BackendSettingsSocialRouteImport
      parentRoute: typeof BackendSettingsRouteRoute
    }
    '/backend/settings/payments': {
      id: '/backend/settings/payments'
      path: '/payments'
      fullPath: '/backend/settings/payments'
      preLoaderRoute: typeof BackendSettingsPaymentsRouteImport
      parentRoute: typeof BackendSettingsRouteRoute
    }
    '/backend/settings/navigation': {
      id: '/backend/settings/navigation'
      path: '/navigation'
      fullPath: '/backend/settings/navigation'
      preLoaderRoute: typeof BackendSettingsNavigationRouteImport
      parentRoute: typeof BackendSettingsRouteRoute
    }
    '/backend/settings/footer': {
      id: '/backend/settings/footer'
      path: '/footer'
      fullPath: '/backend/settings/footer'
      preLoaderRoute: typeof BackendSettingsFooterRouteImport
      parentRoute: typeof BackendSettingsRouteRoute
    }
    '/backend/settings/branding': {
      id: '/backend/settings/branding'
      path: '/branding'
      fullPath: '/backend/settings/branding'
      preLoaderRoute: typeof BackendSettingsBrandingRouteImport
      parentRoute: typeof BackendSettingsRouteRoute
    }
    '/backend/settings/apps': {
      id: '/backend/settings/apps'
      path: '/apps'
      fullPath: '/backend/settings/apps'
      preLoaderRoute: typeof BackendSettingsAppsRouteImport
      parentRoute: typeof BackendSettingsRouteRoute
    }
    '/backend/inbox/submissions': {
      id: '/backend/inbox/submissions'
      path: '/inbox/submissions'
      fullPath: '/backend/inbox/submissions'
      preLoaderRoute: typeof BackendInboxSubmissionsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/content/videos': {
      id: '/backend/content/videos'
      path: '/content/videos'
      fullPath: '/backend/content/videos'
      preLoaderRoute: typeof BackendContentVideosRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/content/venture': {
      id: '/backend/content/venture'
      path: '/content/venture'
      fullPath: '/backend/content/venture'
      preLoaderRoute: typeof BackendContentVentureRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/content/trust-content': {
      id: '/backend/content/trust-content'
      path: '/content/trust-content'
      fullPath: '/backend/content/trust-content'
      preLoaderRoute: typeof BackendContentTrustContentRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/content/stories': {
      id: '/backend/content/stories'
      path: '/content/stories'
      fullPath: '/backend/content/stories'
      preLoaderRoute: typeof BackendContentStoriesRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/content/quran-wiki': {
      id: '/backend/content/quran-wiki'
      path: '/content/quran-wiki'
      fullPath: '/backend/content/quran-wiki'
      preLoaderRoute: typeof BackendContentQuranWikiRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/content/quran-editions': {
      id: '/backend/content/quran-editions'
      path: '/content/quran-editions'
      fullPath: '/backend/content/quran-editions'
      preLoaderRoute: typeof BackendContentQuranEditionsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/content/hero': {
      id: '/backend/content/hero'
      path: '/content/hero'
      fullPath: '/backend/content/hero'
      preLoaderRoute: typeof BackendContentHeroRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/content/books': {
      id: '/backend/content/books'
      path: '/content/books'
      fullPath: '/backend/content/books'
      preLoaderRoute: typeof BackendContentBooksRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/content/articles': {
      id: '/backend/content/articles'
      path: '/content/articles'
      fullPath: '/backend/content/articles'
      preLoaderRoute: typeof BackendContentArticlesRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/commerce/products': {
      id: '/backend/commerce/products'
      path: '/commerce/products'
      fullPath: '/backend/commerce/products'
      preLoaderRoute: typeof BackendCommerceProductsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/commerce/donations': {
      id: '/backend/commerce/donations'
      path: '/commerce/donations'
      fullPath: '/backend/commerce/donations'
      preLoaderRoute: typeof BackendCommerceDonationsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/account/orders/$reference': {
      id: '/account/orders/$reference'
      path: '/account/orders/$reference'
      fullPath: '/account/orders/$reference'
      preLoaderRoute: typeof AccountOrdersReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BackendSettingsRouteRouteChildren {
  BackendSettingsAppsRoute: typeof BackendSettingsAppsRoute
  BackendSettingsBrandingRoute: typeof BackendSettingsBrandingRoute
  BackendSettingsFooterRoute: typeof BackendSettingsFooterRoute
  BackendSettingsNavigationRoute: typeof BackendSettingsNavigationRoute
  BackendSettingsPaymentsRoute: typeof BackendSettingsPaymentsRoute
  BackendSettingsSocialRoute: typeof BackendSettingsSocialRoute
  BackendSettingsUsersRoute: typeof BackendSettingsUsersRoute
  BackendSettingsIndexRoute: typeof BackendSettingsIndexRoute
}

const BackendSettingsRouteRouteChildren: BackendSettingsRouteRouteChildren = {
  BackendSettingsAppsRoute: BackendSettingsAppsRoute,
  BackendSettingsBrandingRoute: BackendSettingsBrandingRoute,
  BackendSettingsFooterRoute: BackendSettingsFooterRoute,
  BackendSettingsNavigationRoute: BackendSettingsNavigationRoute,
  BackendSettingsPaymentsRoute: BackendSettingsPaymentsRoute,
  BackendSettingsSocialRoute: BackendSettingsSocialRoute,
  BackendSettingsUsersRoute: BackendSettingsUsersRoute,
  BackendSettingsIndexRoute: BackendSettingsIndexRoute,
}

const BackendSettingsRouteRouteWithChildren =
  BackendSettingsRouteRoute._addFileChildren(BackendSettingsRouteRouteChildren)

interface BackendRouteRouteChildren {
  BackendSettingsRouteRoute: typeof BackendSettingsRouteRouteWithChildren
  BackendArticlesRoute: typeof BackendArticlesRoute
  BackendBooksRoute: typeof BackendBooksRoute
  BackendDonationsRoute: typeof BackendDonationsRoute
  BackendForgotPasswordRoute: typeof BackendForgotPasswordRoute
  BackendHeroRoute: typeof BackendHeroRoute
  BackendLoginRoute: typeof BackendLoginRoute
  BackendProductsRoute: typeof BackendProductsRoute
  BackendQuranEditionsRoute: typeof BackendQuranEditionsRoute
  BackendQuranWikiRoute: typeof BackendQuranWikiRoute
  BackendResetPasswordRoute: typeof BackendResetPasswordRoute
  BackendSignupRoute: typeof BackendSignupRoute
  BackendSiteRoute: typeof BackendSiteRoute
  BackendStoriesRoute: typeof BackendStoriesRoute
  BackendTrustContentRoute: typeof BackendTrustContentRoute
  BackendUsersRoute: typeof BackendUsersRoute
  BackendVentureRoute: typeof BackendVentureRoute
  BackendVideosRoute: typeof BackendVideosRoute
  BackendIndexRoute: typeof BackendIndexRoute
  BackendCommerceDonationsRoute: typeof BackendCommerceDonationsRoute
  BackendCommerceProductsRoute: typeof BackendCommerceProductsRoute
  BackendContentArticlesRoute: typeof BackendContentArticlesRoute
  BackendContentBooksRoute: typeof BackendContentBooksRoute
  BackendContentHeroRoute: typeof BackendContentHeroRoute
  BackendContentQuranEditionsRoute: typeof BackendContentQuranEditionsRoute
  BackendContentQuranWikiRoute: typeof BackendContentQuranWikiRoute
  BackendContentStoriesRoute: typeof BackendContentStoriesRoute
  BackendContentTrustContentRoute: typeof BackendContentTrustContentRoute
  BackendContentVentureRoute: typeof BackendContentVentureRoute
  BackendContentVideosRoute: typeof BackendContentVideosRoute
  BackendInboxSubmissionsRoute: typeof BackendInboxSubmissionsRoute
  BackendSubmissionsContactRoute: typeof BackendSubmissionsContactRoute
  BackendSubmissionsDistributorRoute: typeof BackendSubmissionsDistributorRoute
  BackendSubmissionsFreeQuranRoute: typeof BackendSubmissionsFreeQuranRoute
  BackendSubmissionsIndexRoute: typeof BackendSubmissionsIndexRoute
}

const BackendRouteRouteChildren: BackendRouteRouteChildren = {
  BackendSettingsRouteRoute: BackendSettingsRouteRouteWithChildren,
  BackendArticlesRoute: BackendArticlesRoute,
  BackendBooksRoute: BackendBooksRoute,
  BackendDonationsRoute: BackendDonationsRoute,
  BackendForgotPasswordRoute: BackendForgotPasswordRoute,
  BackendHeroRoute: BackendHeroRoute,
  BackendLoginRoute: BackendLoginRoute,
  BackendProductsRoute: BackendProductsRoute,
  BackendQuranEditionsRoute: BackendQuranEditionsRoute,
  BackendQuranWikiRoute: BackendQuranWikiRoute,
  BackendResetPasswordRoute: BackendResetPasswordRoute,
  BackendSignupRoute: BackendSignupRoute,
  BackendSiteRoute: BackendSiteRoute,
  BackendStoriesRoute: BackendStoriesRoute,
  BackendTrustContentRoute: BackendTrustContentRoute,
  BackendUsersRoute: BackendUsersRoute,
  BackendVentureRoute: BackendVentureRoute,
  BackendVideosRoute: BackendVideosRoute,
  BackendIndexRoute: BackendIndexRoute,
  BackendCommerceDonationsRoute: BackendCommerceDonationsRoute,
  BackendCommerceProductsRoute: BackendCommerceProductsRoute,
  BackendContentArticlesRoute: BackendContentArticlesRoute,
  BackendContentBooksRoute: BackendContentBooksRoute,
  BackendContentHeroRoute: BackendContentHeroRoute,
  BackendContentQuranEditionsRoute: BackendContentQuranEditionsRoute,
  BackendContentQuranWikiRoute: BackendContentQuranWikiRoute,
  BackendContentStoriesRoute: BackendContentStoriesRoute,
  BackendContentTrustContentRoute: BackendContentTrustContentRoute,
  BackendContentVentureRoute: BackendContentVentureRoute,
  BackendContentVideosRoute: BackendContentVideosRoute,
  BackendInboxSubmissionsRoute: BackendInboxSubmissionsRoute,
  BackendSubmissionsContactRoute: BackendSubmissionsContactRoute,
  BackendSubmissionsDistributorRoute: BackendSubmissionsDistributorRoute,
  BackendSubmissionsFreeQuranRoute: BackendSubmissionsFreeQuranRoute,
  BackendSubmissionsIndexRoute: BackendSubmissionsIndexRoute,
}

const BackendRouteRouteWithChildren = BackendRouteRoute._addFileChildren(
  BackendRouteRouteChildren,
)

interface DonateCheckoutRouteChildren {
  DonateCheckoutCancelRoute: typeof DonateCheckoutCancelRoute
  DonateCheckoutPaypalReturnRoute: typeof DonateCheckoutPaypalReturnRoute
  DonateCheckoutSuccessRoute: typeof DonateCheckoutSuccessRoute
}

const DonateCheckoutRouteChildren: DonateCheckoutRouteChildren = {
  DonateCheckoutCancelRoute: DonateCheckoutCancelRoute,
  DonateCheckoutPaypalReturnRoute: DonateCheckoutPaypalReturnRoute,
  DonateCheckoutSuccessRoute: DonateCheckoutSuccessRoute,
}

const DonateCheckoutRouteWithChildren = DonateCheckoutRoute._addFileChildren(
  DonateCheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackendRouteRoute: BackendRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DistributeRoute: DistributeRoute,
  OrderFreeQuransRoute: OrderFreeQuransRoute,
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  ApiPaypalWebhookRoute: ApiPaypalWebhookRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  BooksSlugRoute: BooksSlugRoute,
  DonateSlugRoute: DonateSlugRoute,
  DonateCartRoute: DonateCartRoute,
  DonateCheckoutRoute: DonateCheckoutRouteWithChildren,
  QuranSlugRoute: QuranSlugRoute,
  VideosSlugRoute: VideosSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  DonateIndexRoute: DonateIndexRoute,
  QuranIndexRoute: QuranIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
  VideosIndexRoute: VideosIndexRoute,
  AccountOrdersReferenceRoute: AccountOrdersReferenceRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
